### PR TITLE
Introduce a :nulldb_postgres adapter for providing postgres features.

### PR DESCRIPTION
**Pull request by Empact**
This is not quite ready for merge, but I want to put it up for discussion. Currently nulldb blows up if you use any of the fancy new postgres features that Rails 4 rolls out. I set about getting them working an this is my approach: creating a minimal second adapter which extends the first, and adding some extension points to enable them to operate against one another.

The main concern I have at this point is not knowing how to reliable identify the original adapter type of the database, before it was nullified. I have it working in nulldb_rspec, but not in nulldb/core.

Any thoughts/advice would be appreciated.

### CODE REVIEW

**Comment by mnoack** [comment]
@Empact @mckinnsb @erkki @kshmir I have just been added as a maintainer to nulldb. If this PR can be rebased off master, passed the tests I'll gladly look into it.

**Comment by atodorov** [comment]
@mnoack I think I'll also need this PR merged b/c I have PostreSQL and JSON fields and trying to get NullDB working. I will be poking around the code in the next following days to get myself familiar. If the OP doesn't respond I will try to rebase this PR and see how it goes.

**Comment by mnoack** [comment]
@atodorov If someone can rebase this PR off master of nulldb, and it passes the tests I'm more than happy to review and hopefully merge.

Even if you rebase and PR so we can at least see what tests are failing (e.g. I suspect rails 5 will fail in this PR - but this PR was done at a time when rails5 wasn't supported or tested against) and I can assist if needed.

**Comment by mnoack** [comment]
@atodorov I'm closing this because I haven't heard back, but I definitely welcome postgres support. The key thing I would be looking for in any future PR is the test side to ensure automated tests can cover this change.

**Pull request closed without merging**
