### PR TITLE
Add ability to set the TableDefinition class.

### PR DESCRIPTION
**Pull request by michaelgpearce**
The table definition class can be set via passing
in `:table_definition_class_name` as a connection
parameter.

This is specifically useful when the default 
table definition does not support the column types
in the schema.rb. Specifically, passing in
`ActiveRecord::ConnectionAdapters::PostgreSQL::TableDefinition`
allows column types such as `json` to exist in the
schema.

### CODE REVIEW

**Comment by mnoack** [comment]
@michaelgpearce - I don't suppose you can write a test for this? I'm happy with the PR change as is.

**Comment by michaelgpearce** [comment]
The spec would be difficult to write - probably requiring a different database adapter and checking it. Probably an order of magnitude more difficult that the code change itself.

**Comment by mnoack** [comment]
I won't release a gem just yet. If you don't mind using it from master so that it gets some real testing before I cut a release. You can do this easily in a gemfile.

**Comment by michaelgpearce** [comment]
Sounds good.

**Pull request merged**
