### PR TITLE
Add ActiveRecord 8.0 support

### PR DESCRIPTION
**Pull request by simpl1g**
Fixes compatiblity with Rails/ActiveRecord 8.0
All tests should be passing with Rails master branch

Cheers to @taylorthurlow for work on AR 7.2 support

### CODE REVIEW

**Comment by garytaylor** [comment]
+1 - This one is holding back our rails upgrades.  I can always switch to the repo/branch of this PR of course but would prefer to wait for the main gem to be updated ideally

**Comment by taylorthurlow** [comment]
@cabello Sorry for the ping, the README says you are the current maintainer for this repo. This is holding up folks with Rails 7.2 (and 8) upgrades, any chance you have time to review?

**Comment by cabello** [comment]
I can take a look at this next week, as I stopped working with Rails I need to find a way to give this project away to a suitable maintainer.

**Comment by gstokkink** [comment]
@cabello thanks! Also thanks for your hard work over the years maintaining this gem, much appreciated. Should've been part of Rails by now, given how useful it is 😀

**Comment by gstokkink** [comment]
@cabello thanks a lot! 😄

**Pull request merged**
