### PR TITLE
Rails5

### PR DESCRIPTION
**Pull request by mnoack**
Adapts existing AR 4.2 fixes, improves legacy support and adds rails 5 support.

All tests pass on travis.

Attn: @blaet @avdi

### CODE REVIEW

**Comment by blaet** [comment]
@mnoack thanks for putting this together! I've merged changes for AR 4.2 support separately. Can you rebase this PR on the changes in the master branch?

**Comment by mnoack** [comment]
@blaet done. I've also taken the opportunity to clean it up a bit. It passes all tests (https://travis-ci.org/mnoack/nulldb/builds/149079577)

Note I've added ruby 1.9 support because I feel it's technically needed whilst you have a rails 2.3 gemfile, but I would completely support dropping ruby 1.9 and rails 2 (and perhaps even rails 3 for that matter) and those wanting these gems can stick to existing versions and we can enforce a minimum in the gemspec.

Feel free to ignore that commit if you're dropping rails 2 support.

**Comment by mnoack** [comment]
Bump @blaet - Let me know if there is anything more you need from me.

**Comment by mnoack** [comment]
One more note on this PR, whilst it fixes the tests for rails5, it has an issue for me locally when running nulldb with our 'no database at all' unit specs.

It seems in rails 5 activerecord tries to load fixtures so I've had to override it to be null, I'm not sure if this is the appropriate solution at this stage as we're still trying to get our test suite to pass.

```ruby
# Stop fixtures getting in way of non nulldb specs
# Fixes case where you run bundle exec rspec spec/unit
# Because this runs both spec_helper_nulldb and spec_helper_lite specs
# Doesn't play nicely since rspec-rails loads FixtureSupport (rspec/rails/configuration.rb)
# Which means after nulldb is loaded (loading activerecord)
# the spec_helper_lite fixtures now want to load fixtures which they can't
module ActiveRecord
  module TestFixtures
    def before_setup
      super
    end

    def after_teardown
      super
    end
  end
end
```

**Comment by edwardmp** [comment]
I see this pull requests also fixes the issue I'm having (see https://github.com/nulldb/nulldb/issues/69). Hope this can be merged in soon!

**Comment by mnoack** [comment]
Time for my monthly bump @blaet - Let me know if you need help

**Comment by mnoack** [comment]
Hi other maintainers (@ardsrk @avdi @isaacsanders @mattvanhorn @myronmarston @woahdae)
It would be really good if you can assist me and @blaet in getting this (and perhaps other PR's) through. I'm happy to be given access to do this, or for you guys to do so.

Thanks for all the good work, it's an awesome gem.

**Comment by isaacsanders** [comment]
I will add y'all if the others don't object. I have been grossly negligent, and would be happy to pass the helm.

**Comment by edwardmp** [comment]
What still needs to be done before this can be merged in?

**Comment by mnoack** [comment]
@isaacsanders I see :+1: from 2 other maintainers and no objections (at least publicly :))

**Comment by isaacsanders** [comment]
LGTM.

**Comment by mnoack** [comment]
Thank you very much @isaacsanders. Merged. I've added a changelog, bumped the version in improve_release branch (see: https://github.com/nulldb/nulldb/compare/master...nulldb:improve_release?expand=1) but I've also cleaned up the release process to replace jeweler with bundler and other things that I do in my own gems, happy for you to review, merge and release or let me do it.

To release I need a gem I eed further permissions, by adding me as a gem owner:
gem owner activerecord-nulldb-adapter -a michael@noack.com.au
Source: http://guides.rubygems.org/command-reference/#gem_owner

or I can let you guys review, merge and release it (I shouldn't be releasing the gem often, maybe once a month)

**Comment by isaacsanders** [comment]
What do you all think wrt @mnoack's request, @nulldb/team-nulldb?

**Comment by mnoack** [comment]
Bump @nulldb/team-nulldb

**Comment by mattvanhorn** [comment]
LGTM 👍  Go for it.

**Comment by isaacsanders** [comment]
One more team member's approval and I will add. Thanks for your patience, @mnoack.

**Comment by myronmarston** [comment]
Go for it.

**Comment by isaacsanders** [comment]
Done. Welcome @mnoack

**Pull request merged**
