### PR TITLE
Add support for ActiveRecord 6.0

### PR DESCRIPTION
**Pull request by coorasse**
Adds support for Rails 6.0 and adds ruby 2.5 and 2.6 to the build matrix on Travis.

### CODE REVIEW

**Comment by scones** [comment]
```
An error occurred while loading spec_helper.
Failure/Error: require 'nulldb_rspec'

NameError:
  uninitialized constant ActiveRecord::ConnectionAdapters::SchemaDumper
  Did you mean?  ActiveRecord::ConnectionAdapters::SchemaCache
# /home/scones/.rbenv/versions/2.6.2/gemsets/dsa/gems/activerecord-6.0.0.rc1/lib/active_record/connection_adapters/abstract/schema_dumper.rb:5:in `<module:ConnectionAdapters>'
# /home/scones/.rbenv/versions/2.6.2/gemsets/dsa/gems/activerecord-6.0.0.rc1/lib/active_record/connection_adapters/abstract/schema_dumper.rb:4:in `<module:ActiveRecord>'
# /home/scones/.rbenv/versions/2.6.2/gemsets/dsa/gems/activerecord-6.0.0.rc1/lib/active_record/connection_adapters/abstract/schema_dumper.rb:3:in `<top (required)>'
# /home/scones/.rbenv/versions/2.6.2/gemsets/dsa/gems/activerecord-6.0.0.rc1/lib/active_record/connection_adapters/abstract_adapter.rb:6:in `<top (required)>'
# /home/scones/.rbenv/versions/2.6.2/gemsets/dsa/gems/activerecord-nulldb-adapter-0.3.9/lib/active_record/connection_adapters/nulldb_adapter.rb:7:in `<top (required)>'
# /home/scones/.rbenv/versions/2.6.2/gemsets/dsa/gems/activerecord-nulldb-adapter-0.3.9/lib/nulldb_rspec.rb:1:in `<top (required)>'
# ./spec/spec_helper.rb:1:in `<top (required)>'
# ------------------
# --- Caused by: ---
# LoadError:
#   cannot load such file -- nulldb_rspec
#   ./spec/spec_helper.rb:1:in `<top (required)>'
```

I am getting this error on your branch tho.

I am not sure, if i set it up incorrectly, or if this is a problem with the branch.

**Comment by coorasse** [comment]
does it happen also for the master branch of the gem on github? or only on my branch?

**Comment by scones** [comment]
yes, same error.

**Comment by scones** [comment]
```
Failure/Error: require 'nulldb_rspec'

NameError:
  uninitialized constant ActiveRecord::ConnectionAdapters::SchemaDumper
  Did you mean?  ActiveRecord::ConnectionAdapters::SchemaCache

# /home/scones/.rbenv/versions/2.6.2/gemsets/dsa/gems/activerecord-6.0.0.rc1/lib/active_record/connection_adapters/abstract/schema_dumper.rb:5:in `<module:ConnectionAdapters>'
# /home/scones/.rbenv/versions/2.6.2/gemsets/dsa/gems/activerecord-6.0.0.rc1/lib/active_record/connection_adapters/abstract/schema_dumper.rb:4:in `<module:ActiveRecord>'
# /home/scones/.rbenv/versions/2.6.2/gemsets/dsa/gems/activerecord-6.0.0.rc1/lib/active_record/connection_adapters/abstract/schema_dumper.rb:3:in `<top (required)>'
# /home/scones/.rbenv/versions/2.6.2/gemsets/dsa/gems/activerecord-6.0.0.rc1/lib/active_record/connection_adapters/abstract_adapter.rb:6:in `require'
# /home/scones/.rbenv/versions/2.6.2/gemsets/dsa/gems/activerecord-6.0.0.rc1/lib/active_record/connection_adapters/abstract_adapter.rb:6:in `<top (required)>'
# /home/scones/.rbenv/versions/2.6.2/gemsets/dsa/gems/activerecord-nulldb-adapter-0.3.9/lib/active_record/connection_adapters/nulldb_adapter.rb:7:in `require'
# /home/scones/.rbenv/versions/2.6.2/gemsets/dsa/gems/activerecord-nulldb-adapter-0.3.9/lib/active_record/connection_adapters/nulldb_adapter.rb:7:in `<top (required)>'
# /home/scones/.rbenv/versions/2.6.2/gemsets/dsa/gems/activerecord-nulldb-adapter-0.3.9/lib/nulldb_rspec.rb:1:in `require'
# /home/scones/.rbenv/versions/2.6.2/gemsets/dsa/gems/activerecord-nulldb-adapter-0.3.9/lib/nulldb_rspec.rb:1:in `<top (required)>'
# ./spec/spec_helper.rb:1:in `require'
```

**Comment by monotek** [comment]
The build seems to be green meanwhile.
Any chance to see this merged soon?

**Comment by mnoack** [comment]
Is someone able to be a maintainer of this project. You don't need to do too much, just oversee PR's like this and review/merge as needed (you can then review/merge this diff).

Ping me if you're interested and I can add you to the project.

Unfortunately I don't use this project anymore so I have stepped back to facilitate others who are able to maintain it.

**Comment by monotek** [comment]
I guess i'm not the right person but what about creating a pinned "call for maintainers" issue?

**Comment by mnoack** [comment]
I think we can find a maintainer. Feel free to post an issue and mention people who might be interested, people here are all forking this project (and then others are using this code) so there's already lots of effort to use this code.

I think the main issue is people think they are signing up for work (they aren't). They are probably going to just review one Pull Request every month and it'll be a easy merge or request changes.

Or people are worried they are now responsible (they aren't, those who update the gem need to test, and it's only a test gem anyway).

**Comment by coorasse** [comment]
if you have the permissions, add me and I'll merge and release 😄

**Comment by gregorw** [comment]
> […] it's only a test gem anyway.

We use it in production ;)

**Comment by cabello** [comment]
I am just waiting on @mnoack to sort it out how we gonna publish the next release to Rubygems. :)

**Comment by mnoack** [comment]
@cabello What's your rubygems email so I can give you permission, also I'll get it done quicker if you can tell me the command to run, from memory it's something like "gem owner nulldb --add youremail"

**Comment by cabello** [comment]
@mnoack `gem owner --add danilo.cabello@gmail.com nulldb`

**Comment by mnoack** [comment]
Done.

**Comment by thelastinuit** [comment]
> ```
> Failure/Error: require 'nulldb_rspec'
> 
> NameError:
>   uninitialized constant ActiveRecord::ConnectionAdapters::SchemaDumper
>   Did you mean?  ActiveRecord::ConnectionAdapters::SchemaCache
> 
> # /home/scones/.rbenv/versions/2.6.2/gemsets/dsa/gems/activerecord-6.0.0.rc1/lib/active_record/connection_adapters/abstract/schema_dumper.rb:5:in `<module:ConnectionAdapters>'
> # /home/scones/.rbenv/versions/2.6.2/gemsets/dsa/gems/activerecord-6.0.0.rc1/lib/active_record/connection_adapters/abstract/schema_dumper.rb:4:in `<module:ActiveRecord>'
> # /home/scones/.rbenv/versions/2.6.2/gemsets/dsa/gems/activerecord-6.0.0.rc1/lib/active_record/connection_adapters/abstract/schema_dumper.rb:3:in `<top (required)>'
> # /home/scones/.rbenv/versions/2.6.2/gemsets/dsa/gems/activerecord-6.0.0.rc1/lib/active_record/connection_adapters/abstract_adapter.rb:6:in `require'
> # /home/scones/.rbenv/versions/2.6.2/gemsets/dsa/gems/activerecord-6.0.0.rc1/lib/active_record/connection_adapters/abstract_adapter.rb:6:in `<top (required)>'
> # /home/scones/.rbenv/versions/2.6.2/gemsets/dsa/gems/activerecord-nulldb-adapter-0.3.9/lib/active_record/connection_adapters/nulldb_adapter.rb:7:in `require'
> # /home/scones/.rbenv/versions/2.6.2/gemsets/dsa/gems/activerecord-nulldb-adapter-0.3.9/lib/active_record/connection_adapters/nulldb_adapter.rb:7:in `<top (required)>'
> # /home/scones/.rbenv/versions/2.6.2/gemsets/dsa/gems/activerecord-nulldb-adapter-0.3.9/lib/nulldb_rspec.rb:1:in `require'
> # /home/scones/.rbenv/versions/2.6.2/gemsets/dsa/gems/activerecord-nulldb-adapter-0.3.9/lib/nulldb_rspec.rb:1:in `<top (required)>'
> # ./spec/spec_helper.rb:1:in `require'
> ```
> 
> different trace tho.

@scones  did you manage a workaround?

**Comment by thelastinuit** [comment]
> ```
> An error occurred while loading spec_helper.
> Failure/Error: require 'nulldb_rspec'
> 
> NameError:
>  uninitialized constant ActiveRecord::ConnectionAdapters::SchemaDumper
>  Did you mean?  ActiveRecord::ConnectionAdapters::SchemaCache
> # /home/scones/.rbenv/versions/2.6.2/gemsets/dsa/gems/activerecord-6.0.0.rc1/lib/active_record/connection_adapters/abstract/schema_dumper.rb:5:in `<module:ConnectionAdapters>'
> # /home/scones/.rbenv/versions/2.6.2/gemsets/dsa/gems/activerecord-6.0.0.rc1/lib/active_record/connection_adapters/abstract/schema_dumper.rb:4:in `<module:ActiveRecord>'
> # /home/scones/.rbenv/versions/2.6.2/gemsets/dsa/gems/activerecord-6.0.0.rc1/lib/active_record/connection_adapters/abstract/schema_dumper.rb:3:in `<top (required)>'
> # /home/scones/.rbenv/versions/2.6.2/gemsets/dsa/gems/activerecord-6.0.0.rc1/lib/active_record/connection_adapters/abstract_adapter.rb:6:in `<top (required)>'
> # /home/scones/.rbenv/versions/2.6.2/gemsets/dsa/gems/activerecord-nulldb-adapter-0.3.9/lib/active_record/connection_adapters/nulldb_adapter.rb:7:in `<top (required)>'
> # /home/scones/.rbenv/versions/2.6.2/gemsets/dsa/gems/activerecord-nulldb-adapter-0.3.9/lib/nulldb_rspec.rb:1:in `<top (required)>'
> # ./spec/spec_helper.rb:1:in `<top (required)>'
> # ------------------
> # --- Caused by: ---
> # LoadError:
> #   cannot load such file -- nulldb_rspec
> #   ./spec/spec_helper.rb:1:in `<top (required)>'
> ```
> 
> I am getting this error on your branch tho.
> 
> I am not sure, if i set it up incorrectly, or if this is a problem with the branch.

@scones 
I found the reason: https://github.com/nulldb/nulldb/pull/100

**Comment by scones** [comment]
> > ```
> > Failure/Error: require 'nulldb_rspec'
> > 
> > NameError:
> >   uninitialized constant ActiveRecord::ConnectionAdapters::SchemaDumper
> >   Did you mean?  ActiveRecord::ConnectionAdapters::SchemaCache
> > 
> > # /home/scones/.rbenv/versions/2.6.2/gemsets/dsa/gems/activerecord-6.0.0.rc1/lib/active_record/connection_adapters/abstract/schema_dumper.rb:5:in `<module:ConnectionAdapters>'
> > # /home/scones/.rbenv/versions/2.6.2/gemsets/dsa/gems/activerecord-6.0.0.rc1/lib/active_record/connection_adapters/abstract/schema_dumper.rb:4:in `<module:ActiveRecord>'
> > # /home/scones/.rbenv/versions/2.6.2/gemsets/dsa/gems/activerecord-6.0.0.rc1/lib/active_record/connection_adapters/abstract/schema_dumper.rb:3:in `<top (required)>'
> > # /home/scones/.rbenv/versions/2.6.2/gemsets/dsa/gems/activerecord-6.0.0.rc1/lib/active_record/connection_adapters/abstract_adapter.rb:6:in `require'
> > # /home/scones/.rbenv/versions/2.6.2/gemsets/dsa/gems/activerecord-6.0.0.rc1/lib/active_record/connection_adapters/abstract_adapter.rb:6:in `<top (required)>'
> > # /home/scones/.rbenv/versions/2.6.2/gemsets/dsa/gems/activerecord-nulldb-adapter-0.3.9/lib/active_record/connection_adapters/nulldb_adapter.rb:7:in `require'
> > # /home/scones/.rbenv/versions/2.6.2/gemsets/dsa/gems/activerecord-nulldb-adapter-0.3.9/lib/active_record/connection_adapters/nulldb_adapter.rb:7:in `<top (required)>'
> > # /home/scones/.rbenv/versions/2.6.2/gemsets/dsa/gems/activerecord-nulldb-adapter-0.3.9/lib/nulldb_rspec.rb:1:in `require'
> > # /home/scones/.rbenv/versions/2.6.2/gemsets/dsa/gems/activerecord-nulldb-adapter-0.3.9/lib/nulldb_rspec.rb:1:in `<top (required)>'
> > # ./spec/spec_helper.rb:1:in `require'
> > ```
> > 
> > 
> > different trace tho.
> 
> @scones did you manage a workaround?

@thelastinuit no, i uncommented the gem and mocked all Models. so i actually had to set up a test db on my production mysql server to ensure flawless CI/CD. not the best solution, but it works.

but it seems like you found a solution yourself.

**Pull request merged**
