### PR TITLE
Rails 5.1 compatibility

### PR DESCRIPTION
**Pull request by edwardmp**

### CODE REVIEW

**Comment by mnoack** [comment]
@edwardmp Excellent! - Is it too much to ask to add a file to the gemfiles directory (look at the rails 5.0 one) and do a rails 5.1 one. And then add this to the .travis.yml in the root directory and see if that passes travis, that way we might expose any other 5.1 issues.

**Comment by edwardmp** [comment]
Sure I'll look into it

**Comment by edwardmp** [comment]
@mnoack should be added. Also changed Gemspec so that this gem can't be used with a future Rails 5.2 automatically (to prevent issues).

**Comment by mnoack** [comment]
I'm not sure why Travis wasn't automatically run (I'll have to investigate).

I've put travis to automatically run every night no matter what, which I hope will mean I can then remove the gemspec restriction (I can then have a gemfile which will use the latest rails, e.g. 5.2 when it comes out, so that the day 5.2 comes out I'll get a failure email if it's not compatible)

**Comment by edwardmp** [comment]
@mnoack 
It's you're choice, but this choice prevents it completely. If you miss the fail email, existing installations could be broken in the meantime before you catch it. My approach is what you see other gems using.

**Comment by mnoack** [comment]
Fair point.

**Comment by edwardmp** [comment]
@mnoack so the excludes in travis.yml were not correct yet, fixed that. The other tests are failing likely because of changes in AR 5.1 which warrant further investigation.

**Comment by edwardmp** [comment]
@mnoack I suggest you revert this PR for now as there are other incompatible changes in AR 5.1 that we need to solve first.

**Comment by mnoack** [comment]
@edwardmp - Can you review my change to support both rails 5.1 and rails 5.2 - https://github.com/nulldb/nulldb/pull/75

Whilst the tests pass, it would be good for someone who is using rails 5.1 to test it against their own system and maybe highlight if nulldb's test are missing anything.

Thanks!

**Comment by edwardmp** [comment]
@mnoack 
Actually I already tested against 5.1 (my own changes) and I didn't run into any issues. I'll test it against your changes when I have a chance

**Pull request merged**
